### PR TITLE
Upgrade Prelert Kibana swimlane visualization plugin to version 5.1.2

### PR DESCRIPTION
**Pull request by romaindequidt**
- Edits to package.json and README for 5.1.2 & 5.2.2 version
- update lodash methods
- bugfix prelert logo display

You can already test this version (5.1.2) before releasing by doing this:
[prelert_swimlane_vis-5.1.2.zip](https://github.com/prelert/kibana-swimlane-vis/files/888388/prelert_swimlane_vis-5.1.2.zip)
$ curl -Ls --output /tmp/prelert_swimlane_vis-5.1.2.zip "https://github.com/prelert/kibana-swimlane-vis/files/888388/prelert_swimlane_vis-5.1.2.zip"
./kibana-plugin install file:///tmp/prelert_swimlane_vis-5.1.2.zip

You can already test this version (5.2.2) before releasing by doing this:
[prelert_swimlane_vis-5.2.2.zip](https://github.com/prelert/kibana-swimlane-vis/files/888389/prelert_swimlane_vis-5.2.2.zip)
$ curl -Ls --output /tmp/prelert_swimlane_vis-5.2.2.zip "https://github.com/prelert/kibana-swimlane-vis/files/888389/prelert_swimlane_vis-5.2.2.zip"
./kibana-plugin install file:///tmp/prelert_swimlane_vis-5.2.2.zip

### CODE REVIEW

**Comment by bgaston97** [comment]
Don't know if this helps, but I also created a package for 5.1.1
[prelert_swimlane_vis-5.1.1.zip](https://github.com/prelert/kibana-swimlane-vis/files/797749/prelert_swimlane_vis-5.1.1.zip)

**Comment by billmetangmo** [comment]
It helps me :) . Thanks @bgaston97 !

**Comment by pemontto** [comment]
Thanks @romaindequidt and @bgaston97, much appreciated!

**Comment by peteharverson** [comment]
Thanks @romaindequidt for the edits. I've gone ahead and merged your changes. I noted one small typo in the download URL in the README

`https://github.com/prelert/kibana-swimlane-vis/releases/download/v5.0.2/prelert_swimlane_vis-5.1.2.zip`

I'll edit the `v5.0.2` to `v5.1.2` in a separate commit.

I will also put the 5.1.2 and 5.2.2 zip files onto the releases page, plus the 5.1.1 zip you created @bgaston97. Many thanks!

**Pull request merged**
